# Generated by Django 3.1.5 on 2021-01-26 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.TextField(null=True)),
                ('task_category', models.CharField(default='GENERAL', max_length=30)),
                ('task_created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('task_alert_time', models.DateTimeField(default=None, null=True)),
                ('task_done', models.BooleanField(default=False)),
                ('task_archieved', models.BooleanField(default=False)),
            ],
        ),
    ]
